apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: audio-test-rhdh16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audio-test-rhdh16
  name: audio-test-rhdh16
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
